Fixed compilation error in Unity 2019.1 / .NET 4.0
\src\UI\ToastAnimationSettings.cs(19,41): error CS0118: 'Editor' is a namespace but is used like a type

Reason (probably): This imports namespace ModUI.UI, and there is also a namespace ModUI.UI.Editor. Probably best to not have any namespaces called "Editor" but this Pull Request goes the easy route and qualifies UnityEditor.Editor as parent class.